routes:
  - url: "https://go-proxy.test/"
    response:
      rewrite:
        from: ".*"
        to: "https://2nd-proxy.test/"
        regex: true
        proxy: "http://localhost:8084"

  - url: "https://2nd-proxy.test/"
    response:
      rewrite:
        proxy: "http://localhost:8084"

default_route:
  deny_access: true
